# =========================================================
#  VM_GPUWakeup_v1.2.ps1  -  GPU partition 開機喚醒
#                           + registry self-heal
#                           + fallback ICD 註冊路徑全寫
#                           (在 VM 內部執行,不在主機跑)
#
#  v1.2 (新增 fallback ICD 路徑 + FeatureScore boost)
#    Windows OpenGL ICD 查詢路徑不只 Display Class subkey,還有:
#      a) HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers
#         (舊式 ICD 註冊,Java OpenGL / 某些跨平台 loader 會查)
#      b) HKLM\SOFTWARE\WOW6432Node\...\OpenGLDrivers (32-bit fallback)
#      c) HKLM\SOFTWARE\Khronos\OpenGL\Drivers (Khronos-style loader)
#    v1.2 把這 3 個路徑都註冊到當前 nvoglv64.dll,並把 vrd.inf
#    (NVIDIA partition) 的 FeatureScore 拉高、wvmbusvideo (Hyper-V
#    Video) 的 FeatureScore 壓低,試著影響 Windows 主螢幕選擇邏輯。
#    這些都是「純 registry,不裝 VDD / Parsec / Mesa」的最後招式。
#
#  v1.1 (新增 self-heal)
#    主機 NVIDIA driver 升級後,VM 內 HostDriverStore 的
#    nv*.inf_amd64_* 資料夾名字會跟著改 hash:
#       nvmdsi.inf_amd64_549a... (591.74)
#       nvmdi.inf_amd64_41c61b... (596.36)
#       nv_dispi.inf_amd64_67995ce... (更新版)
#    每次 hash 變,registry 內的 OpenGLDriverName 路徑就過期 → GDI Generic
#    v1.1 在每次開機 wakeup 時自動偵測「現在哪個 nv*.inf 資料夾真的有
#    nvoglv64.dll」,把所有 Display Class subkey 內的路徑更新到該位置,
#    順便也修 Khronos Vulkan ICD 註冊。Driver 升級無痛。
#
#  v1.0
#    解決 Hyper-V GPU-PV 場景下「有時 OpenGL 程式打得開,
#    有時打不開」的競態問題:
#
#    開機時若 opengl32.dll 在 NVIDIA driver 完整 init 之前就被
#    第一次查 ICD,結果會 cache 成 GDI Generic;之後就算 NVIDIA
#    醒了,opengl32 還是給 GDI Generic 一直到下次重開機。
#
#    解法:VM 開機自動先做以下動作,把 GPU 完整喚醒,讓 opengl32
#    第一次查到的就是 NVIDIA ICD:
#      1. 等 NVIDIA Display 裝置 PnP 狀態變 OK
#      1.5 (v1.1) 自動修正 registry 內的 OpenGL/UMD/Vulkan 路徑
#      2. 跑 vulkaninfo --summary 觸發 Vulkan init
#      3. 跑 dxdiag /t 觸發 D3D init
#      4. 用 P/Invoke 建一個 OpenGL context 強制 cache NVIDIA ICD
#
#  此工具會:
#    - 在 C:\GPU_Wakeup.ps1 寫一份開機腳本
#    - 建立 SYSTEM 排程「GPU_Wakeup」(AtStartup 觸發)
#    - 立即跑一次,輸出 log 給你看現在狀態
#
#  Log 位置:C:\GPU_Wakeup.log
# =========================================================

$ErrorActionPreference = 'Continue'
try {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $OutputEncoding = [System.Text.Encoding]::UTF8
} catch {}

function W-Title($t) {
    Write-Host ''
    Write-Host ('=' * 60) -ForegroundColor Cyan
    Write-Host (" $t") -ForegroundColor Cyan
    Write-Host ('=' * 60) -ForegroundColor Cyan
}
function W-Step($t) { Write-Host "[*] $t" -ForegroundColor Yellow }
function W-OK($t)   { Write-Host "[+] $t" -ForegroundColor Green }
function W-Err($t)  { Write-Host "[X] $t" -ForegroundColor Red }
function W-Info($t) { Write-Host "    $t" -ForegroundColor Gray }
function W-Warn($t) { Write-Host "[!] $t" -ForegroundColor Yellow }

W-Title 'GPU partition 開機喚醒 + self-heal + fallback ICD v1.2'

Write-Host ''
Write-Host ' 適用情境:' -ForegroundColor White
Write-Host '   - 已用 Host_Master 把 NVIDIA 驅動搬進 VM' -ForegroundColor Gray
Write-Host '   - 有時開機後 OpenGL 程式能跑,有時跳 GDI Generic' -ForegroundColor Gray
Write-Host '   - 想讓「能跑」的機率穩定提高' -ForegroundColor Gray
Write-Host ''

# =========================================================
#  1. 預檢
# =========================================================
W-Step '預檢:管理員權限'
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole] 'Administrator')
if (-not $isAdmin) {
    W-Err '需要系統管理員權限'
    W-Info '請用 .bat 啟動器重跑,它會自動檢查管理員權限'
    exit 1
}
W-OK '管理員權限 OK'

# =========================================================
#  2. 寫 wakeup 腳本到 C:\GPU_Wakeup.ps1
# =========================================================
W-Step '寫入 wakeup 腳本到 C:\GPU_Wakeup.ps1'

$wakeupScript = @'
# GPU_Wakeup.ps1 - auto-generated by VM_GPUWakeup_v1.2
# 開機後喚醒 NVIDIA GPU partition,確保 opengl32.dll 第一次查
# ICD 時會拿到 NVIDIA(而不是退回 GDI Generic)
# v1.2 流程:
#   1. 等 NVIDIA Display PnP ready
#   1.5 self-heal Display Class subkey (driver 升級無痛)
#   1.6 寫 fallback ICD 路徑 + FeatureScore boost
#   2. Vulkan probe
#   3. DXDiag warmup
#   4. OpenGL probe + cache
$ErrorActionPreference = 'Continue'
$logPath = 'C:\GPU_Wakeup.log'
function L($m) { Add-Content -Path $logPath -Value ("[{0}] {1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $m) }

L "=== Wakeup start ==="

# 1. 等 NVIDIA Display PnP 裝置 ready (最多 60 秒)
$retry = 0
$nvReady = $false
while ($retry -lt 30) {
    $nv = Get-PnpDevice -Class 'Display' -FriendlyName 'NVIDIA*' -ErrorAction SilentlyContinue |
          Where-Object { $_.Status -eq 'OK' -and $_.Problem -eq 'CM_PROB_NONE' } |
          Select-Object -First 1
    if ($nv) {
        L "NVIDIA ready: $($nv.InstanceId)"
        $nvReady = $true
        break
    }
    Start-Sleep -Seconds 2
    $retry++
}
if (-not $nvReady) { L "NVIDIA never reached OK state, abort"; return }

# 1.5 (NEW v1.1) - 自動偵測 + 修復 Display Class subkey 內的 OpenGL 路徑
#  主機 driver 更新後,VM 內 nv*.inf_amd64_* 資料夾名稱會跟著變
#  (例如 nvmdsi -> nvmdi -> nv_dispi),registry 若還指舊路徑就 GDI Generic
$realFolder = Get-ChildItem "$env:WinDir\System32\HostDriverStore\FileRepository" -Directory -Filter 'nv*.inf_amd64_*' -ErrorAction SilentlyContinue |
    Where-Object { Test-Path (Join-Path $_.FullName 'nvoglv64.dll') } |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1

if ($realFolder) {
    $newOgl = Join-Path $realFolder.FullName 'nvoglv64.dll'
    $newUmd = Join-Path $realFolder.FullName 'nvldumdx.dll'
    L "Real driver folder: $($realFolder.Name)"

    $displayClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'
    $fixed = 0
    Get-ChildItem $displayClass -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.PSChildName -notmatch '^\d{4}$') { return }
        $p = Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue
        if (-not $p) { return }
        if ($p.InfPath -in @('vrd.inf','wvmbusvideo.inf') -or $p.OpenGLDriverName) {
            $current = if ($p.OpenGLDriverName) { @($p.OpenGLDriverName)[0] } else { '' }
            if ($current -ne $newOgl) {
                New-ItemProperty -Path $_.PSPath -Name 'OpenGLDriverName' -Value @($newOgl) -PropertyType MultiString -Force -ErrorAction SilentlyContinue | Out-Null
                New-ItemProperty -Path $_.PSPath -Name 'OpenGLVersion'    -Value 4096      -PropertyType DWord       -Force -ErrorAction SilentlyContinue | Out-Null
                if (Test-Path $newUmd) {
                    New-ItemProperty -Path $_.PSPath -Name 'UserModeDriverName' -Value @($newUmd,$newUmd,$newUmd,$newUmd) -PropertyType MultiString -Force -ErrorAction SilentlyContinue | Out-Null
                }
                L "  Fixed Sub=$($_.PSChildName) ($($p.DriverDesc)) -> $newOgl"
                $fixed++
            }
        }
    }
    L "Registry self-heal: $fixed subkeys updated"

    # 順便也更新 Khronos Vulkan ICD 註冊 (如果新資料夾有 nv-vk64.json)
    $jsonPath = Join-Path $realFolder.FullName 'nv-vk64.json'
    if (Test-Path $jsonPath) {
        $vkKey = 'HKLM:\SOFTWARE\Khronos\Vulkan\Drivers'
        if (-not (Test-Path $vkKey)) { New-Item -Path $vkKey -Force -ErrorAction SilentlyContinue | Out-Null }
        # 移除指向舊路徑的 nv-vk*.json
        try {
            (Get-Item $vkKey).GetValueNames() | Where-Object { $_ -match 'nv-vk' -and $_ -ne $jsonPath } | ForEach-Object {
                Remove-ItemProperty -Path $vkKey -Name $_ -ErrorAction SilentlyContinue
            }
        } catch {}
        New-ItemProperty -Path $vkKey -Name $jsonPath -Value 0 -PropertyType DWord -Force -ErrorAction SilentlyContinue | Out-Null
        L "Vulkan ICD registered (current path): $jsonPath"
    }
} else {
    L "WARNING: no nv*.inf_amd64_* folder with nvoglv64.dll found, skipping registry fix"
}

# 1.6 (NEW v1.2) - 寫入 Windows OpenGL 的 fallback ICD 註冊路徑
#  Microsoft opengl32.dll 主要查 Display Class subkey,但某些舊式或
#  跨平台 OpenGL loader 會查下面這幾個位置。一網打盡:
#    a) HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers (legacy)
#    b) HKLM\SOFTWARE\WOW6432Node\...\OpenGLDrivers (32-bit)
#    c) HKLM\SOFTWARE\Khronos\OpenGL\Drivers (Khronos-style)
#  + 微調 Display Class FeatureScore 讓 vrd.inf 比 wvmbusvideo.inf
#    在「主螢幕候選」排名更高 (Windows 在某些情況會重選 primary)
if ($realFolder) {
    $ogl64 = Join-Path $realFolder.FullName 'nvoglv64.dll'
    $ogl32 = Join-Path $realFolder.FullName 'nvoglv32.dll'

    # a) 舊式 OpenGLDrivers (64-bit)
    try {
        $key = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers'
        if (-not (Test-Path $key)) { New-Item -Path $key -Force -ErrorAction SilentlyContinue | Out-Null }
        New-ItemProperty -Path $key -Name 'NVIDIA' -Value $ogl64 -PropertyType String -Force -ErrorAction SilentlyContinue | Out-Null
        L "Legacy OpenGLDrivers (64) registered: NVIDIA -> $ogl64"
    } catch { L "Legacy OpenGLDrivers (64) failed: $($_.Exception.Message)" }

    # b) WOW6432 (32-bit fallback)
    try {
        $key = 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers'
        if (-not (Test-Path $key)) { New-Item -Path $key -Force -ErrorAction SilentlyContinue | Out-Null }
        $ogl32target = if (Test-Path $ogl32) { $ogl32 } else { $ogl64 }
        New-ItemProperty -Path $key -Name 'NVIDIA' -Value $ogl32target -PropertyType String -Force -ErrorAction SilentlyContinue | Out-Null
        L "Legacy OpenGLDrivers (WOW6432) registered: NVIDIA -> $ogl32target"
    } catch { L "Legacy OpenGLDrivers (WOW6432) failed: $($_.Exception.Message)" }

    # c) Khronos OpenGL Drivers (跨平台 loader 用)
    try {
        $key = 'HKLM:\SOFTWARE\Khronos\OpenGL\Drivers'
        if (-not (Test-Path $key)) { New-Item -Path $key -Force -ErrorAction SilentlyContinue | Out-Null }
        # 清掉指向舊路徑的 entry
        try {
            (Get-Item $key).GetValueNames() | Where-Object { $_ -ne $ogl64 -and $_ -match 'nvoglv64' } | ForEach-Object {
                Remove-ItemProperty -Path $key -Name $_ -ErrorAction SilentlyContinue
            }
        } catch {}
        New-ItemProperty -Path $key -Name $ogl64 -Value 0 -PropertyType DWord -Force -ErrorAction SilentlyContinue | Out-Null
        L "Khronos OpenGL Drivers registered: $ogl64 = 0"
    } catch { L "Khronos OpenGL Drivers failed: $($_.Exception.Message)" }

    # d) FeatureScore 調整:讓 vrd.inf (NVIDIA partition) 比 wvmbusvideo.inf
    #    (Hyper-V Video) 在 Windows 主螢幕候選排序中分數高,有機會讓
    #    Windows 改選 vrd.inf 為 primary
    $displayClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'
    Get-ChildItem $displayClass -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.PSChildName -notmatch '^\d{4}$') { return }
        $p = Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue
        if (-not $p) { return }
        try {
            if ($p.InfPath -eq 'vrd.inf') {
                New-ItemProperty -Path $_.PSPath -Name 'FeatureScore' -Value 0xFF -PropertyType DWord -Force -ErrorAction SilentlyContinue | Out-Null
                L "  Sub=$($_.PSChildName) (vrd.inf) FeatureScore = 0xFF (boost)"
            }
            if ($p.InfPath -eq 'wvmbusvideo.inf') {
                New-ItemProperty -Path $_.PSPath -Name 'FeatureScore' -Value 0x10 -PropertyType DWord -Force -ErrorAction SilentlyContinue | Out-Null
                L "  Sub=$($_.PSChildName) (wvmbusvideo.inf) FeatureScore = 0x10 (lower)"
            }
        } catch {}
    }
    L "Fallback ICD paths + FeatureScore tweaks done"
}

# 2. 觸發 Vulkan init (如果有 vulkaninfo)
$vkInfo = Get-ChildItem 'C:\Windows\System32\HostDriverStore\FileRepository\nv*.inf_amd64_*\vulkaninfo-x64.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
if ($vkInfo) {
    try {
        & $vkInfo.FullName --summary 2>&1 | Out-Null
        L "Vulkan probe OK ($($vkInfo.FullName))"
    } catch {
        L "Vulkan probe error: $($_.Exception.Message)"
    }
}

# 3. 觸發 D3D 初始化 (dxdiag headless)
$dxOut = "$env:TEMP\dx_warmup.txt"
try {
    & dxdiag /t $dxOut
    Start-Sleep 5
    if (Test-Path $dxOut) {
        L "DXDiag warmup OK"
        Remove-Item $dxOut -Force -ErrorAction SilentlyContinue
    }
} catch {
    L "DXDiag warmup error: $($_.Exception.Message)"
}

# 4. 觸發 OpenGL context + 強制 cache NVIDIA ICD
try {
    Add-Type @"
using System;
using System.Runtime.InteropServices;
public class GLW {
    [DllImport("user32.dll")] public static extern IntPtr GetDC(IntPtr h);
    [DllImport("user32.dll")] public static extern int ReleaseDC(IntPtr h, IntPtr dc);
    [DllImport("gdi32.dll")] public static extern int ChoosePixelFormat(IntPtr dc, ref PFD p);
    [DllImport("gdi32.dll")] public static extern bool SetPixelFormat(IntPtr dc, int f, ref PFD p);
    [DllImport("opengl32.dll")] public static extern IntPtr wglCreateContext(IntPtr dc);
    [DllImport("opengl32.dll")] public static extern bool wglMakeCurrent(IntPtr dc, IntPtr rc);
    [DllImport("opengl32.dll")] public static extern IntPtr glGetString(uint n);
    [DllImport("opengl32.dll")] public static extern bool wglDeleteContext(IntPtr rc);
    [StructLayout(LayoutKind.Sequential)]
    public struct PFD {
        public ushort nSize, nVersion;
        public uint dwFlags;
        public byte iPixelType, cColorBits, cRedBits, cRedShift, cGreenBits, cGreenShift, cBlueBits, cBlueShift, cAlphaBits, cAlphaShift;
        public byte cAccumBits, cAccumRedBits, cAccumGreenBits, cAccumBlueBits, cAccumAlphaBits;
        public byte cDepthBits, cStencilBits, cAuxBuffers, iLayerType, bReserved;
        public uint dwLayerMask, dwVisibleMask, dwDamageMask;
    }
}
"@ -ErrorAction Stop

    $dc = [GLW]::GetDC([IntPtr]::Zero)
    $pfd = New-Object GLW+PFD
    $pfd.nSize = 40; $pfd.nVersion = 1; $pfd.dwFlags = 0x25
    $pfd.iPixelType = 0; $pfd.cColorBits = 32; $pfd.cDepthBits = 24
    $pf = [GLW]::ChoosePixelFormat($dc, [ref]$pfd)
    [void][GLW]::SetPixelFormat($dc, $pf, [ref]$pfd)
    $rc = [GLW]::wglCreateContext($dc)
    if ($rc -ne [IntPtr]::Zero -and [GLW]::wglMakeCurrent($dc, $rc)) {
        $vendor   = [System.Runtime.InteropServices.Marshal]::PtrToStringAnsi([GLW]::glGetString(0x1F00))
        $renderer = [System.Runtime.InteropServices.Marshal]::PtrToStringAnsi([GLW]::glGetString(0x1F01))
        $version  = [System.Runtime.InteropServices.Marshal]::PtrToStringAnsi([GLW]::glGetString(0x1F02))
        L "GL_VENDOR  : $vendor"
        L "GL_RENDERER: $renderer"
        L "GL_VERSION : $version"
        if ($renderer -match 'NVIDIA') {
            L "OK: OpenGL ICD bound to NVIDIA"
            Set-Content -Path 'C:\GPU_Wakeup_OK' -Value $renderer -ErrorAction SilentlyContinue
        } else {
            L "FAIL: OpenGL fell back to: $renderer"
            Remove-Item 'C:\GPU_Wakeup_OK' -ErrorAction SilentlyContinue
        }
        [void][GLW]::wglMakeCurrent($dc, [IntPtr]::Zero)
        [void][GLW]::wglDeleteContext($rc)
    } else {
        L "wglCreateContext / MakeCurrent failed"
    }
    [void][GLW]::ReleaseDC([IntPtr]::Zero, $dc)
} catch {
    L "OpenGL probe exception: $($_.Exception.Message)"
}

L "=== Wakeup done ==="
'@

$wakeupPath = 'C:\GPU_Wakeup.ps1'
try {
    Set-Content -Path $wakeupPath -Value $wakeupScript -Encoding UTF8 -Force
    W-OK "已寫入: $wakeupPath"
} catch {
    W-Err "寫入失敗: $($_.Exception.Message)"
    exit 1
}

# =========================================================
#  3. 註冊開機排程
# =========================================================
W-Step "註冊排程 GPU_Wakeup (AtStartup,SYSTEM 帳號執行)"

try {
    Unregister-ScheduledTask -TaskName 'GPU_Wakeup' -Confirm:$false -ErrorAction SilentlyContinue

    $action    = New-ScheduledTaskAction -Execute 'powershell.exe' `
                  -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$wakeupPath`""
    $trigger   = New-ScheduledTaskTrigger -AtStartup
    $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -RunLevel Highest
    $settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries `
                  -DontStopIfGoingOnBatteries -ExecutionTimeLimit (New-TimeSpan -Minutes 3)

    Register-ScheduledTask -TaskName 'GPU_Wakeup' -Action $action -Trigger $trigger `
                          -Principal $principal -Settings $settings `
                          -Description 'Wake up NVIDIA GPU partition before OpenGL apps' `
                          -Force | Out-Null

    W-OK "排程已建立: GPU_Wakeup"
    W-Info "  腳本: $wakeupPath"
    W-Info "  觸發: 每次開機"
    W-Info "  Log : C:\GPU_Wakeup.log"
} catch {
    W-Err "排程建立失敗: $($_.Exception.Message)"
    exit 1
}

# =========================================================
#  4. 立即跑一次,看當前狀態
# =========================================================
W-Step '立即跑一次 wakeup,看當前 OpenGL 狀態'

# 清掉舊 log,看這次跑的結果
Remove-Item 'C:\GPU_Wakeup.log' -Force -ErrorAction SilentlyContinue
Remove-Item 'C:\GPU_Wakeup_OK' -Force -ErrorAction SilentlyContinue

try {
    Start-ScheduledTask -TaskName 'GPU_Wakeup'
    W-Info '排程已觸發,等 30 秒讓它跑完...'
    Start-Sleep -Seconds 30

    if (Test-Path 'C:\GPU_Wakeup.log') {
        Write-Host ''
        Write-Host '  --- C:\GPU_Wakeup.log ---' -ForegroundColor Cyan
        Get-Content 'C:\GPU_Wakeup.log' | ForEach-Object { Write-Host "  $_" }
        Write-Host '  --------------------------' -ForegroundColor Cyan
    }

    if (Test-Path 'C:\GPU_Wakeup_OK') {
        $renderer = (Get-Content 'C:\GPU_Wakeup_OK' -Raw).Trim()
        Write-Host ''
        W-OK "本次 OpenGL ICD 綁到 NVIDIA: $renderer"
        Write-Host '   --> 現在可以開 L1C / 任何 OpenGL 程式' -ForegroundColor Green
    } else {
        Write-Host ''
        W-Warn '本次 wakeup 沒搶到 NVIDIA ICD,opengl32 cache 仍是 GDI Generic'
        W-Info '處理方式:重開 VM 一次,排程會自動再跑'
        W-Info '          看 C:\GPU_Wakeup.log 是否最終 GL_RENDERER 顯示 NVIDIA'
    }
} catch {
    W-Err "立即觸發失敗: $($_.Exception.Message)"
}

# =========================================================
#  5. 結尾
# =========================================================
W-Title '完成'
Write-Host ''
Write-Host ' 之後使用方式:' -ForegroundColor White
Write-Host '   1. VM 重開機' -ForegroundColor Gray
Write-Host '   2. 登入後等 30-60 秒讓排程跑完' -ForegroundColor Gray
Write-Host '   3. 看 C:\GPU_Wakeup.log 最後幾行確認' -ForegroundColor Gray
Write-Host '      GL_RENDERER 是 NVIDIA 才開遊戲' -ForegroundColor Gray
Write-Host '   4. 如果是 GDI Generic,再重開 VM 一次' -ForegroundColor Gray
Write-Host ''
Write-Host ' 預期效果:' -ForegroundColor White
Write-Host '   - 「OpenGL 能跑」的機率從隨機提升到大多數' -ForegroundColor Gray
Write-Host '   - 偶爾還是會中失敗模式,重開 VM 即可' -ForegroundColor Gray
Write-Host ''
